ALTER TABLE [dbo].[UsersInRoles] ADD  CONSTRAINT [UQ_UsersInRoles_UserId_RoleId] UNIQUE NONCLUSTERED 
(
	[UserId] ASC, 
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO